apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dims-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: dims-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: dims-cluster-role
  apiGroup: rbac.authorization.k8s.io

