apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dims-cluster-role  
rules:
- apiGroups: [""]  # Core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: [""]  # API group for pod logs
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]  # Core API group
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["networking.k8s.io"]  # Correct API group for ingress-related resources
  resources: ["ingresses"]
  verbs: ["create", "list", "watch"]
- apiGroups: ["traefik.containo.us"]  # API group for traefik ingresses
  resources: ["ingressroutes"]
  verbs: ["patch", "get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["apps"]  # Apps API group for deployments
  resources: ["deployments"]
  verbs: ["create", "list", "watch", "update"]
- apiGroups: ["apps"]  # To handle rollout of deployments
  resources: ["deployments/scale"]  # Allows scaling operations which can be part of a rollout
  verbs: ["update"]
- apiGroups: ["apps"]  # To handle rollout of deployments
  resources: ["deployments/status"]  # Allows checking the status of a deployment rollout
  verbs: ["get", "list", "watch"]

