apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: scheduler

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
spec:
  selector:
    matchLabels:
      app: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - image: swensadocker/dims-scheduler:1.0.0-102
          name: scheduler
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: '3306'    
            - name: DB_NAME
              value: dimsdb
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: _GENERATE_PASSWORD_           
            - name: INTEGRATIONS
              value: '01:00'      
            - name: ISERUN
              value: "60" 
            - name: DNACRUN
              value: "23:55"    
            - name: ISEDNAC_BACK_DAYS
              value: "1"      
            - name: ISEDNAC_CHECK_INTERVAL
              value: "5"                    